### ISSUE TITLE
We should add a license to the repo.

### ISSUE THREAD

**Issue by JTWWilson** [CSSUoB/cssuob.github.io#325]
I think discussion in the Discord has landed on the MIT license: https://opensource.org/licenses/MIT

**Comment by jedevc** [comment]
Copyright holder should be "CSS website authors" or something similar. Importantly, it can't be "CSS", since that would imply transferring copyright to the society, which isn't the intention (and also requires a CLA, and is not wonderful, especially since there's no intention to re-license the site).

**Comment by Danyc0** [comment]
I'd much prefer Apache
