### ISSUE TITLE
Enhancements to /agendas

### ISSUE THREAD

**Issue by Vishwas-Adiga** [CSSUoB/cssuob.github.io#357]
In its current state, the `/agendas` page is fairly barebones and requires manual upkeep. I propose the following enhancements:

- [x] List agenda items in reverse chronological order
- [ ] Allow for filtering between AGM/EGM and committee meeting agendas
- [ ] Distinguish between `<h2>` and `<h3>` in the list (which are currently formatted the same except for font weight)
- [ ] Add blurb on what agendas are and outline what the documents listed entail
- [ ] If renaming existing documents is a non-issue, consider automating the addition of new items to the list by pulling from `assets/agendas` and formatting list items based on more descriptive document names

**Comment by Vishwas-Adiga** [comment]
Re the last point, thoughts on appending `_agm` or `_egm` to existing agenda docs for AGMs and EGMs? 
So eg `/assets/agendas/agenda_22_10_27.pdf` would become `/assets/agendas/agenda_22_10_27_egm.pdf`

**Comment by MattyTheHacker** [comment]
yeah I like the idea of the file names being distinguishable, in fact because of today (27th, so yesterday now, I suppose) the file names will need to be different between EGM/AGMs and normal meetings as we had an EGM and a normal meeting on the same day. 

I think I might prefer `egm_agenda_date_blah_blah` as opposed to `agenda_date_blah_blah_egm` but I'm not too bothered either way.

**Comment by Vishwas-Adiga** [comment]
Having the agenda date first makes it significantly easier to to group and sort all agendas, which is why I prefer that format.

**Comment by MattyTheHacker** [comment]
ah yes that is very true, I hadn't thought of that
